{{- include "vectis.validate" . -}}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vectis.secretName" . }}
  labels:
    {{- include "vectis.labels" . | nindent 4 }}
type: Opaque
stringData:
  init.json: |-
{{ .Values.secrets.initJson | nindent 4 }}
  .unseal_key: |-
{{ .Values.secrets.unsealKey | nindent 4 }}
  config.json: |-
{{ .Values.secrets.configJson | nindent 4 }}
  config_sign.json: |-
{{ .Values.secrets.configSignJson | nindent 4 }}
  VECTIS_APIKEY_HASH: {{ .Values.secrets.apiKeyHash | quote }}
  VECTIS_POSTGRES_DSN: {{ .Values.secrets.postgresDsn | quote }}
{{- if .Values.vectis.tls.enabled }}
  tls.crt: |-
{{ .Values.secrets.tlsCert | nindent 4 }}
  tls.key: |-
{{ .Values.secrets.tlsKey | nindent 4 }}
{{- end }}
{{- end }}
